version: "3.2"

services:
  vscode:
    image: latexdevcontainer
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/root/.ssh
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - TZ=
    # This delayed entrypoint shell execution is a workaround 
    # for a bug introduced in VS Code v1.64 
    # that prevents initial handshake between the IDE 
    # to the newly created container
    entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
